/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/inspect-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect */
        post: operations["inspect_api_imports_inspect_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Status */
        get: operations["import_status_api_imports__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session List */
        get: operations["session_list_api_replay_sessions_get"];
        put?: never;
        /** Sessions */
        post: operations["sessions_api_replay_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Session Delete */
        delete: operations["session_delete_api_replay_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/close-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Close All */
        post: operations["session_close_all_api_replay_sessions__session_id__close_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Fills
         * @description One bounded page of the session's fill history (newest first).
         */
        get: operations["session_fills_api_replay_sessions__session_id__fills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/indicators/{indicator_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Indicators */
        post: operations["indicators_api_replay_sessions__session_id__indicators__indicator_id__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/orders/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Orders */
        post: operations["orders_api_replay_sessions__session_id__orders_market_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Settings */
        patch: operations["settings_api_replay_sessions__session_id__settings_patch"];
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session State */
        get: operations["session_state_api_replay_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_replay_sessions__session_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Step */
        post: operations["session_step_api_replay_sessions__session_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Trades
         * @description One bounded page of the session's trade history (newest first).
         *
         *     Closed trades include review notes/tags; an unknown or foreign-session
         *     cursor is rejected with 400.
         */
        get: operations["session_trades_api_replay_sessions__session_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/sessions/{session_id}/trades/{trade_id}/chart-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Trade Chart
         * @description A bounded historical chart window anchored around one (possibly old) trade.
         */
        get: operations["session_trade_chart_api_replay_sessions__session_id__trades__trade_id__chart_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Symbols */
        get: operations["symbols_api_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/{symbol}/ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranges */
        get: operations["ranges_api_symbols__symbol__ranges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeframe-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles */
        get: operations["profiles_api_timeframe_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_api_trades__trade_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review
         * @description Persist the user review (note + tags) for one session trade.
         */
        patch: operations["review_api_trades__trade_id__review_patch"];
        trace?: never;
    };
    "/api/trades/{trade_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stop */
        put: operations["stop_api_trades__trade_id__stop_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}/target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Target */
        put: operations["target_api_trades__trade_id__target_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChartHistoryResponse
         * @description A bounded historical chart window anchored around one (possibly old)
         *     trade.
         *
         *     The window holds enough source candles around the trade for the chart to
         *     focus on it; it never loads the entire session's chart and does not
         *     recreate the chart instance on the client. The trade's own fills come
         *     from the authoritative fill ledger (the trade may no longer be in the
         *     bounded in-memory working set).
         */
        ChartHistoryResponse: {
            /** Displayed Bars */
            displayed_bars: components["schemas"]["DisplayBar"][];
            /** Fills */
            fills: components["schemas"]["Fill"][];
            /** Indicators */
            indicators: {
                [key: string]: components["schemas"]["IndicatorPoint"][];
            };
            trade: components["schemas"]["Trade"];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** CloseRequest */
        CloseRequest: {
            /** Quantity */
            quantity: number;
            /** Session Id */
            session_id: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Deleted */
            deleted: boolean;
            /** Id */
            id: string;
        };
        /** DisplayBar */
        DisplayBar: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Is Partial */
            is_partial: boolean;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Source 1M End Time */
            source_1m_end_time: string | null;
            /** Source 1M Start Time */
            source_1m_start_time: string | null;
            /** Timeframe */
            timeframe: string;
            /** Timestamp */
            timestamp: string;
            /** Volume */
            volume: number;
        };
        /** Fill */
        Fill: {
            /** Commission */
            commission: number;
            /** Execution Window End */
            execution_window_end: string | null;
            /** Execution Window Start */
            execution_window_start: string | null;
            /** Gross Pnl */
            gross_pnl: number;
            /** Id */
            id: string;
            /** Market Price */
            market_price: number | null;
            /** Pnl */
            pnl: number;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
            /** Session Id */
            session_id: string;
            /** Slippage Cost */
            slippage_cost: number;
            /** Source Candle Time */
            source_candle_time: string;
            /** Spread Cost */
            spread_cost: number;
            /**
             * Time Precision
             * @enum {string}
             */
            time_precision: "exact" | "bar_interval" | "legacy";
            /** Timestamp */
            timestamp: string;
            /** Trade Id */
            trade_id: string;
        };
        /**
         * FillHistoryPage
         * @description One page of a session's fill history (newest first, cursor-based).
         *
         *     `next_cursor` is null on the final page.
         */
        FillHistoryPage: {
            /** Items */
            items: components["schemas"]["Fill"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatch */
        ImportBatch: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Rows Imported */
            rows_imported: number;
            /** Schema Id */
            schema_id: string;
            /** Source Path */
            source_path: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            validation?: components["schemas"]["ImportValidation"] | null;
            /** Validation Json */
            validation_json?: string | null;
        };
        /** ImportRequest */
        ImportRequest: {
            /**
             * Asset Class
             * @default forex
             */
            asset_class: string;
            /**
             * Contract Multiplier
             * @default 1
             */
            contract_multiplier: number;
            /**
             * Default Profile
             * @default utc_aligned
             * @enum {string}
             */
            default_profile: "utc_aligned" | "new_york_close";
            /** Path */
            path: string;
            /**
             * Pnl Currency
             * @default USD
             */
            pnl_currency: string;
            /**
             * Price Precision
             * @default 5
             */
            price_precision: number;
            /** Symbol */
            symbol: string;
        };
        /** ImportValidation */
        ImportValidation: {
            /**
             * Duplicates
             * @default 0
             */
            duplicates: number;
            /**
             * Gap Count
             * @default 0
             */
            gap_count: number;
            /**
             * Invalid Numeric
             * @default 0
             */
            invalid_numeric: number;
            /**
             * Invalid Ohlc
             * @default 0
             */
            invalid_ohlc: number;
            /**
             * Invalid Timestamps
             * @default 0
             */
            invalid_timestamps: number;
            /**
             * Invalid Volume
             * @default 0
             */
            invalid_volume: number;
            /**
             * Source Non Monotonic
             * @default false
             */
            source_non_monotonic: boolean;
            /**
             * Subminute
             * @default 0
             */
            subminute: number;
        };
        /** IndicatorPoint */
        IndicatorPoint: {
            /** Time */
            time: string;
            /** Value */
            value: number;
        };
        /** InspectPathResponse */
        InspectPathResponse: {
            /** Files */
            files: string[];
            /** Kind */
            kind: string;
        };
        /** MarketOrderRequest */
        MarketOrderRequest: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            /** Quantity */
            quantity: number;
            /** Stop Price */
            stop_price?: number | null;
            /** Target Price */
            target_price?: number | null;
        };
        /** PathRequest */
        PathRequest: {
            /** Path */
            path: string;
        };
        /** PriceRequest */
        PriceRequest: {
            /** Price */
            price?: number | null;
            /** Session Id */
            session_id: string;
        };
        /**
         * ReplaySnapshot
         * @description The full bounded authoritative state of a session.
         *
         *     Sent on session creation, resume, and explicit refresh/reconciliation.
         *     `revision` is the persisted revision the snapshot was read from. History
         *     is bounded: every open trade plus the most recent closed trades and
         *     fills; the `*_total` fields and truncation flags say how much more
         *     exists in the authoritative tables (fetched via the history endpoints).
         *     The internal statistics accumulator is never exposed.
         */
        ReplaySnapshot: {
            /** Account Currency */
            account_currency: string;
            /** Advance Step Minutes */
            advance_step_minutes: number;
            /** Chart Context 1M Bars */
            chart_context_1m_bars: number;
            /** Closed Trades Total */
            closed_trades_total: number;
            /** Closed Trades Truncated */
            closed_trades_truncated: boolean;
            /** Commission Per Quantity */
            commission_per_quantity: number;
            /** Contract Multiplier */
            contract_multiplier?: number | null;
            /** Conversion Rate */
            conversion_rate: number;
            /** Current Candle Time */
            current_candle_time: string | null;
            /** Current Index */
            current_index: number;
            /** Current Market Time */
            current_market_time: string | null;
            /** Current Price */
            current_price: number | null;
            /** Data Version */
            data_version?: string | null;
            /** Displayed Bars */
            displayed_bars: components["schemas"]["DisplayBar"][];
            /** Enabled Indicators */
            enabled_indicators: string[];
            /** End */
            end: string;
            /** Fills */
            fills: components["schemas"]["Fill"][];
            /** Fills Total */
            fills_total: number;
            /** Fills Truncated */
            fills_truncated: boolean;
            /** Id */
            id: string;
            /** Indicator Warmup Margin */
            indicator_warmup_margin: number;
            /** Indicators */
            indicators: {
                [key: string]: components["schemas"]["IndicatorPoint"][];
            };
            /** Initial Balance */
            initial_balance: number;
            /** Pnl Currency */
            pnl_currency?: string | null;
            /** Price Precision */
            price_precision?: number | null;
            /** Profile */
            profile: string;
            /** Remaining Bars */
            remaining_bars: number;
            /** Revision */
            revision: number;
            /** Slippage */
            slippage: number;
            /** Spread */
            spread: number;
            /** Start */
            start: string;
            stats: components["schemas"]["SessionStats"];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
            /** Symbol */
            symbol: string;
            /** Trades */
            trades: components["schemas"]["Trade"][];
            /** Visible Timeframe */
            visible_timeframe: string;
            /** Warnings */
            warnings: string[];
        };
        /**
         * ReplayUpdate
         * @description A mutation delta for an installed snapshot.
         *
         *     Sent by every replay mutation (step, orders, closes, stop/target moves,
         *     settings, indicator toggles). `revision` is the revision the mutation
         *     committed (after the commit, never a speculative in-memory value), so a
         *     client can reject stale updates (`revision <= installed`), apply the
         *     next one (`revision == installed + 1`), and fetch a fresh snapshot on a
         *     gap (`revision > installed + 1`). The chart remains a full bounded
         *     payload; the history is delta-based.
         */
        ReplayUpdate: {
            /** Advance Step Minutes */
            advance_step_minutes: number;
            /** Closed Trades Total */
            closed_trades_total: number;
            /** Current Candle Time */
            current_candle_time: string | null;
            /** Current Index */
            current_index: number;
            /** Current Market Time */
            current_market_time: string | null;
            /** Current Price */
            current_price: number | null;
            /** Displayed Bars */
            displayed_bars: components["schemas"]["DisplayBar"][];
            /** Enabled Indicators */
            enabled_indicators: string[];
            /** Fills Total */
            fills_total: number;
            /** Id */
            id: string;
            /** Indicators */
            indicators: {
                [key: string]: components["schemas"]["IndicatorPoint"][];
            };
            /** New Fills */
            new_fills: components["schemas"]["Fill"][];
            /** Newly Closed Trades */
            newly_closed_trades: components["schemas"]["Trade"][];
            /** Remaining Bars */
            remaining_bars: number;
            /** Revision */
            revision: number;
            stats: components["schemas"]["SessionStats"];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed";
            /** Trade Removals From Open */
            trade_removals_from_open: string[];
            /** Trade Upserts */
            trade_upserts: components["schemas"]["Trade"][];
            /** Visible Timeframe */
            visible_timeframe: string;
            /** Warnings */
            warnings: string[];
        };
        /**
         * ReviewRecord
         * @description The persisted review (note + tags) for one trade.
         *
         *     Review mutations return this small dedicated record — not a replay
         *     snapshot or update — because they change no replay state and must not
         *     bump the session revision.
         */
        ReviewRecord: {
            /** Note */
            note: string;
            /** Session Id */
            session_id: string;
            /** Tags */
            tags: string[];
            /** Trade Id */
            trade_id: string;
            /** Updated At */
            updated_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Review Note
             * @default
             */
            review_note: string;
            /** Review Tags */
            review_tags?: string[];
            /** Session Id */
            session_id: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * Account Currency
             * @default USD
             */
            account_currency: string;
            /**
             * Advance Step Minutes
             * @default 1
             */
            advance_step_minutes: number;
            /**
             * Chart Context 1M Bars
             * @default 1000
             */
            chart_context_1m_bars: number;
            /**
             * Commission Per Quantity
             * @default 0
             */
            commission_per_quantity: number;
            /**
             * Conversion Rate
             * @default 1
             */
            conversion_rate: number;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Initial Balance
             * @default 10000
             */
            initial_balance: number;
            /** Profile */
            profile?: ("utc_aligned" | "new_york_close") | null;
            /**
             * Slippage
             * @default 0
             */
            slippage: number;
            /**
             * Spread
             * @default 0
             */
            spread: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Symbol */
            symbol: string;
            /**
             * Visible Timeframe
             * @default 1m
             * @enum {string}
             */
            visible_timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
        };
        /** SessionStats */
        SessionStats: {
            /** Average Holding Seconds */
            average_holding_seconds: number | null;
            /** Average Losing R */
            average_losing_r: number | null;
            /** Average Loss */
            average_loss: number | null;
            /** Average R */
            average_r: number | null;
            /** Average Win */
            average_win: number | null;
            /** Average Win R */
            average_win_r: number | null;
            /** Balance */
            balance: number;
            /** Commission Paid */
            commission_paid: number;
            /** Equity */
            equity: number;
            /** Gross Pnl */
            gross_pnl: number;
            /** Long Pnl */
            long_pnl: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Net Pnl */
            net_pnl: number;
            /** Profit Factor */
            profit_factor: number | null;
            /** Short Pnl */
            short_pnl: number;
            /** Slippage Cost */
            slippage_cost: number;
            /** Spread Cost */
            spread_cost: number;
            /** Total R */
            total_r: number;
            /** Trades Completed */
            trades_completed: number;
            /** Trades Opened */
            trades_opened: number;
            /** Trading Costs */
            trading_costs: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Win Rate */
            win_rate: number | null;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Current Index */
            current_index: number;
            /** End */
            end: string;
            /** Id */
            id: string;
            /** Start */
            start: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Updated At */
            updated_at: string;
        };
        /** SettingsRequest */
        SettingsRequest: {
            /** Advance Step Minutes */
            advance_step_minutes?: number | null;
            /** Visible Timeframe */
            visible_timeframe?: ("1m" | "5m" | "15m" | "1h" | "4h" | "1d") | null;
        };
        /**
         * SymbolMetadata
         * @description One symbol's current instrument/dataset metadata.
         *
         *     `data_version` is null on legacy rows published before immutable dataset
         *     versions existed; such datasets are the then-current source and sessions
         *     created from them pin no version.
         */
        SymbolMetadata: {
            /** Asset Class */
            asset_class: string;
            /** Contract Multiplier */
            contract_multiplier: number;
            /** Data Version */
            data_version?: string | null;
            /** Default Profile */
            default_profile: string;
            /** First Timestamp */
            first_timestamp: string;
            /** Last Timestamp */
            last_timestamp: string;
            /** Pnl Currency */
            pnl_currency: string;
            /** Price Precision */
            price_precision: number;
            /** Symbol */
            symbol: string;
        };
        /** SymbolRange */
        SymbolRange: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Symbol */
            symbol: string;
        };
        /** TimeframeProfile */
        TimeframeProfile: {
            /** Anchor */
            anchor?: string | null;
            /** Default */
            default?: boolean | null;
            /** Id */
            id: string;
            /** Implemented */
            implemented: boolean;
            /** Timezone */
            timezone?: string | null;
        };
        /** Trade */
        Trade: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            /** Entry Market Price */
            entry_market_price: number;
            /** Entry Price */
            entry_price: number;
            /** Entry Source Candle Time */
            entry_source_candle_time: string;
            /** Entry Time */
            entry_time: string;
            /** Exit Market Price */
            exit_market_price: number | null;
            /** Exit Price */
            exit_price: number | null;
            /** Exit Time */
            exit_time: string | null;
            /** Exit Time Precision */
            exit_time_precision: ("exact" | "bar_interval" | "legacy") | null;
            /** Exit Window End */
            exit_window_end: string | null;
            /** Exit Window Start */
            exit_window_start: string | null;
            /** Final Exit Reason */
            final_exit_reason: string | null;
            /** Id */
            id: string;
            /** Initial Quantity */
            initial_quantity: number;
            /** Initial Risk */
            initial_risk: number | null;
            /** Mae Close Price Delta */
            mae_close_price_delta: number | null;
            /** Mae Gross Pnl */
            mae_gross_pnl: number | null;
            /** Mfe Close Price Delta */
            mfe_close_price_delta: number | null;
            /** Mfe Gross Pnl */
            mfe_gross_pnl: number | null;
            /** Realized Pnl */
            realized_pnl: number;
            /** Remaining Quantity */
            remaining_quantity: number;
            /**
             * Review Note
             * @default
             */
            review_note: string;
            /** Review Tags */
            review_tags?: string[];
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /** Stop Price */
            stop_price: number | null;
            /** Target Price */
            target_price: number | null;
            /** Total Commission */
            total_commission: number;
            /** Total Slippage Cost */
            total_slippage_cost: number;
            /** Total Spread Cost */
            total_spread_cost: number;
        };
        /**
         * TradeHistoryPage
         * @description One page of a session's trade history (newest first, cursor-based).
         *
         *     Closed trades include their review notes/tags and normalized legacy
         *     timing; `next_cursor` is null on the final page.
         */
        TradeHistoryPage: {
            /** Items */
            items: components["schemas"]["Trade"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_import_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_api_imports_inspect_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_status_api_imports__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_list_api_replay_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    sessions_api_replay_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_delete_api_replay_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_close_all_api_replay_sessions__session_id__close_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_fills_api_replay_sessions__session_id__fills_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillHistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indicators_api_replay_sessions__session_id__indicators__indicator_id__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                indicator_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_api_replay_sessions__session_id__orders_market_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_replay_sessions__session_id__settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_state_api_replay_sessions__session_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_replay_sessions__session_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_step_api_replay_sessions__session_id__step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_trades_api_replay_sessions__session_id__trades_get: {
        parameters: {
            query?: {
                status?: "open" | "closed";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeHistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_trade_chart_api_replay_sessions__session_id__trades__trade_id__chart_history_get: {
        parameters: {
            query?: {
                context_bars?: number;
            };
            header?: never;
            path: {
                session_id: string;
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    symbols_api_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolMetadata"][];
                };
            };
        };
    };
    ranges_api_symbols__symbol__ranges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolRange"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profiles_api_timeframe_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeframeProfile"][];
                };
            };
        };
    };
    close_api_trades__trade_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_trades__trade_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_trades__trade_id__stop_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_api_trades__trade_id__target_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
